### ISSUE TITLE
Добавить возможности "комментариев"

### ISSUE THREAD

**Issue by lonslaught** [kushedow/skypro-reviewer#10]
Добавить значения, которые могут видеть наставники, чтобы на них ориентироваться. Но данные строки не будут выводиться в ответ.
(Может отдельной колонкой?)

**Comment by kushedow** [comment]
@lonslaught а можешь сказать примеры таких комментариев? Что мы в них будем писать?

**Comment by kushedow** [comment]
Сделано

![image](https://github.com/kushedow/skypro-reviewer/assets/7995387/825faa5d-e95e-4595-893c-6175e2fb176a)
